# Generated by Django 3.0.1 on 2019-12-29 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=10)),
                ('request_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('patient_code', models.IntegerField()),
                ('transaction_id', models.IntegerField(null=True)),
                ('before', models.TextField(max_length=400, null=True)),
                ('after', models.TextField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=40)),
                ('mname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('card_number', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Стадия 1'), (2, 'Стадия 2'), (3, 'Стадия 3'), (4, 'Стадия 4')], default=1)),
                ('urgently', models.BooleanField(default=False)),
                ('payment_type', models.IntegerField(choices=[(1, 'Оплата наличными'), (2, 'Оплата картой')], default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='labapi.Patients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
